name = "PiPWV"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]

[deps]
ClimateERA = "96028d6e-f290-464b-8a03-1e746e0363c3"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GeoRegions = "b001f823-fa75-4bff-bf55-6610c8f3688a"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
GridInterpolations = "bb4c363b-b914-514b-8517-4eb369bc008a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"
