name = "PiPWV"

[deps]
ClimateERA = "96028d6e-f290-464b-8a03-1e746e0363c3"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
ClimateERA = "0.4"
DrWatson = "1"
NCDatasets = "0.9, 0.10"
julia = "1"
